{{- if not .Values.customCaCertUsed }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- with .Values.selfSignedClusterIssuer }}
  name: {{ .name | quote }}
  labels:
  {{- include "common.labels" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- with .Values.caCertificate }}
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "common.labels" $ | nindent 4 }}
spec:
  isCA: true
  commonName: {{ .commonName | quote }}
  secretName: {{ $.Values.caCertSecretName | quote }}
  privateKey:
  {{- .privateKey | toYaml | nindent 4 }}
  issuerRef:
    name: {{ $.Values.selfSignedClusterIssuer.name | quote }}
    kind: ClusterIssuer
    group: cert-manager.io
  {{- end }}
{{- end }}

{{- if .Values.customCaCertUsed }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caCertSecretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
data:
  {{- .Values.customCaCertSecretData | toYaml | nindent 2 }}
{{ end }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.prodClusterIssuer.name | quote }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.caCertSecretName | quote }}
