{{- if not .Values.customCaCertUsed }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- with .Values.caCertificate }}
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- template "common.labels" $ }}
  annotations:
    "helm.sh/hook-weight": "1"
    {{- include "common.annotations" $.Chart | nindent 4 }}
spec:
  isCA: true
  commonName: {{ .commonName | quote }}
  secretName: {{ $.Values.caCertSecretName | quote }}
  privateKey:
  {{- .privateKey | toYaml | nindent 4 }}
  issuerRef:
    name: {{ $.Values.selfSignedClusterIssuer.name | quote }}
    kind: ClusterIssuer
    group: cert-manager.io
  {{- end }}
{{- end }}
