---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.prodClusterIssuer.name | quote }}
  {{- template "common.labels" . }}
spec:
  ca:
    secretName: {{ .Values.caCertSecretName | quote }}
