---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.prodClusterIssuer.name | quote }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.caCertSecretName | quote }}
