{{- if .Values.customCaCertUsed }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caCertSecretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
data:
  {{- .Values.customCaCertSecretData | toYaml | nindent 2 }}
{{ end }}
