{{- if .Values.customCaCertUsed }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caCertSecretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  {{- template "common.labels" . }}
data:
  {{- .Values.customCaCertSecretData | toYaml | nindent 2 }}
{{ end }}
