---
{{- if not .Values.customCaCertUsed }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- with .Values.selfSignedClusterIssuer }}
  name: {{ .name | quote }}
  {{- template "common.labels" $ }}
  annotations:
    "helm.sh/hook-weight": "0"
    {{- include "common.annotations" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
